UserWeb:
  Name: 'user-web'
  GinAddr: "localhost:9000"
  UserSrv:
    Host: '127.0.0.1'
    Port: 9090
  JwtConfig:
    Secret: 'zsj'
    Issuer: 'zsj'
    ExpireMin: 20
    PublicKeyPath: 'user-web/config/publickey'
    PrivateKeyPath: 'user-web/config/privatekey'
  RedisConfig:
    Host: '127.0.0.1'
    Port: 50000
    ExpireMin: 7
