ServiceConfig:
  IP: 'localhost'
  Port: 10010
  SrvName: 'goods_srv'
  DBConfig:
    Host: 'localhost'
    Port: 5432
    User: 'postgres'
    Dbname: 'mxshop_goods'
    Password: 'az123.'
  EtcdConfig:
    EndPoints:
      - 'localhost:2379'
    Prefix: 'goods_srv'
    LeaseSec: 5



